### ISSUE TITLE
Crash/incompatibility

### ISSUE THREAD

**Issue by RaKGEKKO** [Harveykang/AsyncParticles#66]
Hey i found a crash related to Loot beams Up Its a mod for fabric but i use forge, it works fine but crashes when pairing it with your mod.
The version of the game is 1.20.1, and i tested it with only lootbeams and asyncparticles to be sure it was caused by it.

Here is the log and crash report.

[latest.log](https://github.com/user-attachments/files/20007653/latest.log)

[crash-2025-05-01_23.38.39-client.txt](https://github.com/user-attachments/files/20007657/crash-2025-05-01_23.38.39-client.txt)

**Comment by Harveykang** [comment]
That mod is closed-source, hard to fix it. I'll try.

**Comment by RaKGEKKO** [comment]
Should i try to report it to the creator too?

**Comment by Harveykang** [comment]
sure
also it seems that there might be more than just the conflict mentioned in the crash report.
maybe i can fix part of them, but i haven't look into it.

**Comment by RaKGEKKO** [comment]
Well is there something i can do to help?, and btw i didn't find any form of contacting the creator, so i guess its impossible.

**Comment by Harveykang** [comment]
thanks! i'm currently working on the config menu. i'll try decompiling the mod when i get some free time. so just give me a couple days.

**Comment by RaKGEKKO** [comment]
Take your time, your mod is really great thx for making it, and btw its really compatible, i have a 500 mods and it works perfectly fine with everything except that bug.

**Comment by RaKGEKKO** [comment]
Hey, just so you know, i am currently using the forge version of loot beams, its worse but its better than nothing, just telling you in case you can't fix it because its a closed source, its completely fine.
Have a good day. :D

**Comment by Harveykang** [comment]
I'll publish a 2.0.0-alpha.0 on the GitHub Releases page. You can open the config menu (requires Cloth Config) and set the particle rendering mode to 'Compatibility'. This should fix the issue.

In future versions(maybe alpha.2), you may no longer need the 'Compatibility' mode — 'Fastest' should suffice.
I'll keep this issue open until 'Fastest' becomes reliable.

**Comment by RaKGEKKO** [comment]
Thx ill try that version, btw how does the compatibility work?

**Comment by Harveykang** [comment]
By waiting for the async tasks at the vanilla particle stage, instead of at the end of the `renderLevel` method.

**Comment by RaKGEKKO** [comment]
Ok, just to tell you it still crashes with loot beams up. in case it isnt fixable or maybe its some other mod ill check.

[latest.log](https://github.com/user-attachments/files/20137349/latest.log)

[crash-2025-05-10_03.50.16-client.txt](https://github.com/user-attachments/files/20137358/crash-2025-05-10_03.50.16-client.txt)

**Comment by Harveykang** [comment]
try this one please [alpha.1](https://github.com/Harveykang/AsyncParticles/releases/download/v2.0.0-alpha.0/AsyncParticles-2.0.0-alpha.1+1.20.1.jar)
still need Compatibility mode

**Comment by RaKGEKKO** [comment]
Ok ill try.

**Comment by RaKGEKKO** [comment]
It works now :D

![Image](https://github.com/user-attachments/assets/54106aa6-586f-471e-83b1-acafe6b3f65b)

**Comment by RaKGEKKO** [comment]
tysm for everything man.
